const component = {
  ID: "id",
  ID_COMPONENTE: "id_componente",
  CODIGO: "codigo",
  CODE: "code",
  IMAGEN: "imagen",
  IMAGE: "image",
  NRO_PIEZA: "nro_pieza",
  NRO_PART: "nro_part",
  CATEGORIA: "categoria",
  CATEGORY: "category",
  DESCRIPCION: "descripcion",
  DESCRIPTION: "description",
  FABRICANTE: "fabricante",
  MANUFACTURER: "manufacturer",
  STOCK: "stock",
  PRECIO: "precio",
  PRICE: "price",
  TIPO: "tipo",
  VOLTAJE_COLEC_EMIS: "voltaje_colec_emis",
  VOLTAJE_COLEC_BASE: "voltaje_colec_base",
  VOLTAJE_EMIS_BASE: "voltaje_emis_base",
  VOLTAJE_COLEC_EMIS_SAT: "voltaje_colec_emis_sat",
  CORRIENTE_COLEC: "corriente_colec",
  GANANCIA_HFE: "ganancia_hfe",
  DISIP_MAX: "disip_max",
  TEMP_JUNTURA: "temp_juntura",
  HOJA_DE_DATOS:'hoja_de_datos',
  DATASHEET:'datasheet',
  LONGITUD:'longitud',
  LENGTH:'length',
  ANCHO:'ancho',
  WIDTH:'width',
  PESO:'peso',
  WEIGTH:'weigth',
  MATERIAL:'material',
  VOLTAJE_RECOMENDADO:'voltaje_recomendado',
  VOLTAJE_MIN_ENTRADA:'voltaje_min_entrada',
  VOLTAJE_MAX_ENTRADA:'voltaje_max_entrada',
  // Electrolytic Capacitor specific fields
  CAPACITANCIA: "capacitancia",
  TOLERANCIA: "tolerancia",
  RANGO_TEMPERATURA: "rango_temperatura",
  RANGO_TENSION_NOMINAL: "rango_tension_nominal",
  // MOSFET Transistor specific fields
  VOLTAJE_DRENAJE_FUENTE: "voltaje_drenaje_fuente",
  CORRIENTE_CC_DRENAJE: "corriente_cc_drenaje",
  TEMP_OP_MAX: "temp_op_max",
  CONDUCT_DRENAJE_SUSTRATO: "conduct_drenaje_sustrato",
  RESIST_DRENAJE_FUENTE: "resist_drenaje_fuente"
};


module.exports = {
  component
};
